name: Test

on: [pull_request]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: false
            matrix:
                sdk: [Android11Java8, Android11Java11, Android12Java8, Android12Java11, CLINode14, CLINode16, DartBeta, DartStable, Deno1193, Deno1303, DotNet60, DotNet70, FlutterStable, FlutterBeta, Go112, Go118, KotlinJava8, KotlinJava11, KotlinJava17, Node12, Node14, Node16, PHP74, PHP80, Python38, Python39, Python310, Ruby27, Ruby30, Ruby31, AppleSwift55, Swift55, WebChromium, WebNode]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@2.25.2

            - name: Install Dependencies
              run: composer install

            - name: Run Tests
              run: composer test tests/${{ matrix.sdk }}Test.php